### ISSUE TITLE
Build-Task aktualisieren

### ISSUE THREAD

**Issue by hudsonmuff** [joinbox/build-task#17]
Der Build-Task: https://github.com/joinbox/build-task ist veraltet und sollte aktualisiert werden. Verschiedene Dependencies sind deprecated oder es hat peer dependency conflicts.

Ein paar Dependencies welche Probleme mache:
- gulp-better-rollup
- rollup
- babel-eslint

**Comment by fxstr** [comment]
Done with V3: Rollup and Gulp removed; replaced by
- NPM scripts (instead of Gulp) to reduce dependencies
- esbuild instead of Rollup (because it's much faster)
- SWC instead of Babel (because it's much faster)
